### ISSUE TITLE
fix: restore logging embed consistency

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-helper#20]
# Issue

The embed style looks different from the old Rust bot:
 
![image](https://github.com/ReVanced/revanced-helper/assets/13122796/91e4ca33-c98c-4abc-a5f9-b25c20912c8a)

# Solution

- Add the footer
- Add the avatar as the image
- Add the embed color

# Additional context

The embeds themselves also don't look like they are supposed to:

![image](https://github.com/ReVanced/revanced-helper/assets/13122796/ef85da23-7df2-4f4c-a48e-9ce6ca264386)

Instead, they should look like this:

![image](https://github.com/ReVanced/revanced-helper/assets/13122796/536e2d70-a872-4f16-9061-010e444ada56)

![image](https://github.com/ReVanced/revanced-helper/assets/13122796/4fd38e2a-b562-4efd-ae36-0b60fb45da50)

**Comment by reisxd** [comment]
> Add the avatar as the image

The avatar is already added. Discord.js doesn't probably give default avatar URLs, for some reason. Only footer and embed color.

**Comment by oSumAtrIX** [comment]
Not sure, but it should give the users avatar URL which you can then use as the pfp
