### ISSUE TITLE
fix: restore support mute embed style consistency with other embeds

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-helper#21]
# Issue

Embeds look like this: 
![image](https://github.com/ReVanced/revanced-helper/assets/13122796/76d37a62-dbd7-4247-9b82-30dd754237dc)

# Solution

- Add embed color
- Add footer
- Add avatar as image
- Title should say: "Restricted <user> to <channel>", don't emphasise
- Add reason (if any provided)
- Add duration (if any provided)
- Log the event

**Comment by Ushie** [comment]
I believe the exiled message shouldn't contain an embed, and rather simply use the message content directly and suffix it with "@ushie said: ", embeds are kept that way and it's less spammy

**Comment by oSumAtrIX** [comment]
Consistency with other bot responses would be broken and great distinction between a bot message and a user message will also be lost. The slightly additional space the embed would consume is less of an issue than the previous two.

**Comment by reisxd** [comment]
> Title should say: "Restricted to ", don't emphasise

What does this mean?

> Add duration (if any provided)

Exile uses a predefined duration always.
