### ISSUE TITLE
fix: exile command does not transfer messages correctly

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-helper#22]
## Issue

Images or attachments are not logged in the configured channel when using the command, the original message is not deleted.

## Solution

Also consider moving attachments

**Comment by reisxd** [comment]
This would require to download the images or attachments and store it then send it, if we were to delete the orginal message.

Also a reminder, you can only set a single image for embeds. And also no videos for embeds. This'd break "consistency" with the other bot.

**Comment by oSumAtrIX** [comment]
> This would require to download the images or attachments and store it then send it, if we were to delete the orginal message.

Yes, the images will eventually be inaccessible (after a couple days). If that is a problem, you need to download the attachments, and upload them to the new message.

**Comment by reisxd** [comment]
Can there be a field in the embed where all of the attachments links are in there?
Like This:

**Restricted to ...**
**Attachments**
[Image 1](https://example.com)
[Image 2](https://example.com)
[Video 1](https://example.com)

**Orginal Message**
hwo to get peevanc

**Comment by oSumAtrIX** [comment]
Discord eventually restricts access to deleted attachments if the original message is deleted. Also the links wouldn't embed, I think reuploading is necessary for that reason, but it's not really efficient

**Comment by reisxd** [comment]
Reuploading them could take a long time depending on what the member has posted. Also, there's 25MiB file size for uploading content. Which means that Nitro users could upload a bigger content and the bot could not transfer it, unless it gets splitted (which requires more code and more time to transfer the message).

**Comment by oSumAtrIX** [comment]
> Discord eventually restricts access to deleted attachments if the original message is deleted.

A solution for this should be proposed then.

**Comment by PalmDevs** [comment]
Closing as it is tied to #19
