### ISSUE TITLE
fix: Proper syntax support for Telegram and Reddit responses

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-helper#25]
# Issue

Messages are unformatted:
<img src="https://github.com/ReVanced/revanced-helper/assets/13122796/9a26284a-1c3a-4e1c-9956-645687c6ceb1" height=500>

# Solution

Introduce formatting support on Telegram and Reddit client.

**Comment by reisxd** [comment]
Telegram does not support embeds nor normal Markdown. Reddit bot does not work due to no up to date libraries.

**Comment by oSumAtrIX** [comment]
> Telegram does not support embeds nor normal Markdown

I haven't said markdown nor embeds. I said syntax support: https://core.telegram.org/api/entities 

> Reddit bot does not work due to no up to date libraries.

In that case, you can remove the bot from the available clients.

**Comment by oSumAtrIX** [comment]
Is the bot deployed @reisxd

**Comment by reisxd** [comment]
> Is the bot deployed @reisxd If not, please deploy to latest version

It is.

**Comment by oSumAtrIX** [comment]
On our Telegram, the responses still are unformated though

**Comment by reisxd** [comment]
It is formatted.
