### ISSUE TITLE
feat: Whitelist or blacklist channels for responses

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-helper#29]
# Issue

Some responses should only be sent to specific channels on Discord, but you can only whitelist and blacklist specific channels for all responses.

# Solution

Add a way to black or whitelist specific channels for each response.

**Comment by PalmDevs** [comment]
Done in [d3b9e3a](https://github.com/ReVanced/revanced-helper/commit/d3b9e3afeae54a3e14f51ae70ac52db83525bb65)! 🎉
