### ISSUE TITLE
feat(bots/discord): auto-responses via regex

### ISSUE THREAD

**Issue by PalmDevs** [ReVanced/revanced-helper#35]
Something like this basically:

![image](https://github.com/ReVanced/revanced-helper/assets/67689562/9f53774c-e44a-4278-89fb-5d8a34cf219b)

**Comment by oSumAtrIX** [comment]
This already exists in the form of auto-responses. The response can match to any configured string using a regex.

**Comment by PalmDevs** [comment]
In this case, this will stay open to track that on the rewrite branch.
